name: Deploy to EC2

on:
  release:
    types: [published]

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    name: Build & Push Docker Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag stanthikun802/clcm3506-final-exam:$VERSION

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push stanthikun802/clcm3506-final-exam:$VERSION

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_HOST_DNS }}
          REMOTE_USER: ${{ secrets.AWS_EC2_USER }}
          TARGET: ${{ secrets.AWS_TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_DNS }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            docker pull stanthikun802/clcm3506-final-exam:$VERSION
            docker stop clcm3506-final-exam && docker rm clcm3506-final-exam
            docker run -d -p 3000:3000 --name clcm3506-final-exam stanthikun802/clcm3506-final-exam:$VERSION
            docker image prune -f